### PR TITLE
Fix #303: Pending acquire queue has reached its maximum size

### LINKED ISSUE #303: Pending acquire queue has reached its maximum size
When `maxIdleTime` is specified, we start seeing this error:

```log
org.springframework.web.reactive.function.client.WebClientRequestException: Pending acquire queue has reached its maximum size of 32
	at org.springframework.web.reactive.function.client.ExchangeFunctions$DefaultExchangeFunction.lambda$wrapException$9(ExchangeFunctions.java:136)
	Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Request to POST http://localhost:8080/powerauth-java-server/rest/v3/token/validate [DefaultWebClient]
Original Stack Trace:
```

Logic behind `return HttpClient.create(ConnectionProvider.builder("custom").build());` uses different values than `HttpClient.create()`.
See https://github.com/reactor/reactor-netty/issues/2052#issuecomment-1048586578

A follow-up to #187

### PR DESCRIPTION
**Pull request by banterCZ**
- Set max connections to 500 instead of (2 * available number of processors)

### CODE REVIEW

**Review by zcgandcomp — CHANGES_REQUESTED** [review]
This is changing default behavior of the client.

**Review by romanstrobl — APPROVED** [review]
Approved, however please consider if it is a good idea to have "magic" constants in the code.

**Review by romanstrobl — CHANGES_REQUESTED** [review]
I overlooked @zcgandcomp comment, I no longer think this is a good change.

**Comment by banterCZ** [comment]
Ok
@zcgandcomp Let's change to `HttpClient.create()` default, which is 500 connections, calculated size of pending queu 1000, and acquire timeout.
@romanstrobl Yes, it is a magick number, but it is named in our code and the reasoning described in the JavaDoc at least.

**Review by zcgandcomp — APPROVED** [review]
Looks OK

**Review by romanstrobl — APPROVED** [review]
OK.

**Pull request merged**
